dist: trusty
sudo: require

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
  - wget https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.sh
  - sudo sh cmake-3.9.2-Linux-x86_64.sh -- --skip-license --prefix=/usr

script:
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - cd $TRAVIS_BUILD_DIR
  - mkdir cmake_build
  - cd cmake_build
  - cmake -DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/cmake/arm-toolchain.cmake ../ && make doxygen

deploy:
  local_dir: $TRAVIS_BUILD_DIR/build/doxygen/html
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

