/**
 * @file src/version.h
 *
 * @brief Helper header for defining version constants.
 *
 * This file is automatically generated in CMake using the template @c cmake/template/version.h.in. Any modifications
 * will be lost upon the next build.
 */

/*
 * This file is part of RTLib.
 *
 * Copyright (C) 2018 Derppening <david.18.19.21@gmail.com>
 *
 * RTLib is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RTLib is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with RTLib.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef RTLIB_VERSION_H_
#define RTLIB_VERSION_H_

namespace rtlib::version {

constexpr const char* kFull = "0.2.0";
constexpr const unsigned kMajor = 0;
constexpr const unsigned kMinor = 2;
constexpr const unsigned kPatch = 0;

}  // namespace rtlib::version

#endif  // RTLIB_VERSION_H_
